= CloudBees policy utilities

A collection of utilities for working with CloudBees policies.

== Contents

[cols="2a,5a",options="header"]
|===

| Utility
| Description

| link:evaluate-policy-context/README.adoc[evaluate-policy-context]
| Reusable workflow that discovers and evaluates all policies applicable to the current workflow context, and automatically routes `REVIEW` results to a manual approval step.

|===

== Usage

Call `evaluate-policy-context` from your workflow to evaluate all policies that match the current checkpoint.
The workflow resolves `REVIEW` results to a manual approval step automatically.

[source,yaml]
----
policy-exit:
  needs: [scan-job]
  uses: cloudbees-io/policy-utils/evaluate-policy-context/workflow.yml@v2
  with:
    checkpoint-type: job
    checkpoint-name: scan-job
    checkpoint-position: exit
----

See link:evaluate-policy-context/README.adoc[evaluate-policy-context/README.adoc] for the full list of inputs and outputs.

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-unify/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-unify/latest/[the CloudBees platform].
